name: Upstream Sync

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - workflow-to-sync-upstream
      - sync-upstream/*
  schedule:
    - cron: '0 */3 * * *' # every 3 hours
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # Step 1: run a standard checkout action
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SYNC_UPSTREAM_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}

      # Step 2: run the sync action
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: google-gemini/gemini-cli
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.SYNC_UPSTREAM_GITHUB_TOKEN || secrets.GITHUB_TOKEN }} # automatically generated, no need to set

          # Set test_mode true to run tests instead of the true action!!
          test_mode: false
